version: '3.3'
  
volumes:
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:12.17
        env_file:
            - .env
        volumes:
            - db:/var/lib/postgresql/data

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        volumes: 
            - ./backend:/backend
        ports: 
            - 8000:8000
        env_file: 
            - .env